version: '3'
services:

  # Next.js
  nextjs:
    container_name: nextjs
    build:
      context: ./docker-compose/nextjs
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - ./:/var/www

  # Mongodb
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"